name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        agda-ref: ["v2.6.2"]
        ghc-ver: ["8.10.5"]
        stdlib-ref: ["v1.7"]

    steps:
    - uses: actions/cache@v2
      name: Cache stack packages
      id: cache-stack
      with:
        path: |
          ~/.stack
          ~/.local
        key: ${{ runner.os }}-${{ matrix.ghc-ver }}-${{ matrix.agda-ref }}

    - name: Install stack
      if: steps.cache-stack.outputs.cache-hit != 'true'
      uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.ghc-ver }}
        enable-stack: true

    - name: Put stack programs in PATH
      run: echo "~/.local/bin" >> $GITHUB_PATH

    - name: Download Agda from github
      if: steps.cache-stack.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: agda/agda
        path: agda
        ref: ${{ matrix.agda-ref }}

    - name: Install Agda
      if: steps.cache-stack.outputs.cache-hit != 'true'
      run: |
        cd agda
        stack install --stack-yaml stack-8.10.5.yaml

    - name: Checkout stdlib library
      uses: actions/checkout@v2
      with:
        repository: agda/agda-stdlib
        path: agda-stdlib
        ref: ${{ matrix.stdlib-ref }}

    - name: Put stdlib library in Agda library list
      run: |
        mkdir -p ~/.agda/
        touch ~/.agda/libraries
        echo "$GITHUB_WORKSPACE/agda-stdlib/standard-library.agda-lib" > ~/.agda/libraries

    - name: Checkout my library
      uses: actions/checkout@v2
      with:
        path: main

    - name: Typecheck my library
      run: |
        cd main
        agda Everything.agda

