name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Agda
      uses: agda/agda-setup-action@v1.0.0
      with:
        agda-version: "2.8.0"
        agda-stdlib-version: "2.3"

    - name: Checkout my library
      uses: actions/checkout@v4

    - name: Typecheck my library
      run: agda Everything.agda
