name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        agda-ref: ["v2.6.2"]
        ghc-ver: ["8.10.5"]
        stdlib-ref: ["v1.7"]

    steps:
    - name: Setup Agda
      uses: fangyi-zhou/setup-agda-action@main
      with:
        agda-ref: ${{ matrix.agda-ref }}
        ghc-version: ${{ matrix.ghc-ver }}
        stdlib-ref: ${{ matrix.stdlib-ref }}

    - name: Checkout my library
      uses: actions/checkout@v2
      with:
        path: main

    - name: Typecheck my library
      run: |
        cd main
        agda Everything.agda

